# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* auth_faceid
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 17.0\n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "Access denied."
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.js:0
#, python-format
msgid "An error occurred while verifying the face."
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Cancel"
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Capture"
msgstr ""

#. module: auth_faceid
#: model:ir.model.fields,field_description:auth_faceid.field_res_users__face_encoding
msgid "Face Encoding"
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "FaceID Authentication"
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.js:0
#, python-format
msgid "Failed to access the camera."
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Loading..."
msgstr ""

#. module: auth_faceid
#. odoo-javascript
#: code:addons/auth_faceid/static/src/login_faceid/login_faceid.xml:0
#, python-format
msgid "Log in FaceID"
msgstr ""

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No face detected in the captured image."
msgstr ""

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No match found for the captured face."
msgstr ""

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "No users with registered face encodings found."
msgstr ""

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "Session creation error: %(error)s"
msgstr ""

#. module: auth_faceid
#: model:ir.model,name:auth_faceid.model_res_users
msgid "User"
msgstr ""

#. module: auth_faceid
#. odoo-python
#: code:addons/auth_faceid/controllers/main.py:0
#, python-format
msgid "User %(user)s authenticated successfully."
msgstr ""
